displayName=Japanese Plugin
author=Jackpal
support=https://github.com/YS-jack/japanesePlugin
description=translates texts in game to Japanese, can also chat in Japanese
tags=japanese,japan
plugins=com.japanese.JapanesePlugin